%YAML 1.2
---
name: agoncal/agoncal-application-petstore-ee6
home: README.md
resources:
  - https://www.oracle.com/java/index.html
  - url: http://tomee.apache.org/
    title: Apache TomEE
  - http://localhost:8080/javaee-io/project/agoncal/agoncal-application-petstore-ee6/README.md
related:
  - name: tomitribe/crest
    friendly_name: Crest
  - name: AdamBien/enhydrator
    home: README.md


